### ISSUE TITLE
parallel RNG

### ISSUE THREAD

**Issue by GregPlowman** [rfourquet/StableRNGs.jl#1]
Could a RNG be added for parallel use?

Would require a "jump" function or equivalent to produce statistically independent streams.
For use with multi-threading would require thread-safe independence.
As well as higher "rand" functions stability.

[RandomNumbers](https://github.com/sunoru/RandomNumbers.jl) package has some candidate RNGs. In particular, from the `Xorshifts.Xoshiro` family: `Xoshiro256Plus` and `Xoshiro256StarStar`.

**Comment by rfourquet** [comment]
I somewhat feel that for the use case of this package (tests), this feature is probably not needed by many, but would have a quite high maintenance cost.

I'm very unfamiliar with threads in Julia, but currently when threads are involved, it's my understanding that reproducibility is often impossible to achieve, no? But this package's only goal is to support reproducibility... Anyway, for tests, wouldn't it be good enough to initialize different RNGs (on different threads) with randomly looking seeds? Sure nothing is proven, but it might be enough for tests.

> As well as higher "rand" functions stability.

I don't understand what you mean here!

**Comment by GregPlowman** [comment]
OK, fair enough. You make some good points.
